### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Trevoke**
I'm not 100% that this is correct, but I _think_ this is what the README intended to show.

### CODE REVIEW

**Comment by BDav24** [comment]
Yes, you're right! I updated the README but I let the `then` to avoid puting it inside an async function. ~(and subscribe doesn't return the unsubscribe function)~

**Comment by Trevoke** [comment]
Oh, ok - can you tell me what this code means? 

https://github.com/forevertz/node-event-sourcing/blob/master/examples/with-custom-state-store/with-redis/state-reader.js#L21

**Comment by BDav24** [comment]
I edited my comment, subscribe does return the unsubscribe function :sweat_smile:

**Comment by Trevoke** [comment]
Heh, ok - is it worth updating the readme to indicate that?

**Comment by BDav24** [comment]
I'd rather keep the main README very simple, but feel free to propose changes if you think they make things clearer.

**Pull request closed without merging**
